# Generated by Django 2.2.12 on 2020-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
