# Generated by Django 2.2.12 on 2020-04-23 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0004_auto_20200420_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
