# Generated by Django 2.2.12 on 2020-04-23 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0006_selectcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Sites')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Categorys')),
                ('history', models.ManyToManyField(to='wiki.Page')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectCategory',
        ),
    ]
