# Generated by Django 2.2.12 on 2020-04-25 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_auto_20200423_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Categorys'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Sites'),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='Site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Sites'),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Categorys'),
        ),
    ]
