# Generated by Django 2.2.12 on 2020-04-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_settinguser_time_to_new_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguser',
            name='Time_to_new_page',
            field=models.CharField(choices=[('1 ', 'Каждый час'), ('2 ', 'Каждые два часа'), ('3 ', 'Каждые шесть часов'), ('24', 'Каждый день')], max_length=2),
        ),
    ]
