# Generated by Django 2.2.12 on 2020-04-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20200427_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinguser',
            name='Site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.Sites'),
        ),
        migrations.AlterField(
            model_name='settinguser',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.Categorys'),
        ),
    ]
